"""init

Revision ID: f688fa6f552d
Revises: 
Create Date: 2026-04-12 23:06:00.212993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f688fa6f552d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WIN_USER_ONE', 'WIN_USER_TWO', 'DRAW', name='statusgame', native_enum=False), server_default='Active', nullable=False),
    sa.Column('user_one_id', sa.Integer(), nullable=False),
    sa.Column('user_two_id', sa.Integer(), nullable=True),
    sa.Column('user_one_simbol', sa.Enum('X', 'O', name='simbol', native_enum=False), nullable=False),
    sa.Column('user_two_simbol', sa.Enum('X', 'O', name='simbol', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('simbol', sa.Enum('X', 'O', name='simbol', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('number >= 0 AND number <= 8', name='check_turn_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'number', name='uq_game_turn_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turns')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
